In [1]:
import numpy as np
import time

In [1]:
#defining action variables
up=0
down=1
left=2
right=3

#no. of states and no. of variables
noS=3*3
noA=4

S=range(noS)

reward =-1    #for every step

terminal_state = lambda s: s==0  #first and last state terminal

wall=[]

P=dict()  # transition probabilities

# In the dictionary of transition dynamics P[state][action] gives us a tupple which tells us
# the (probability of transition to the next state,
#       next state, 
#       reward the environment gives for the transition,
#       if the environment is done )  

# Hard coding this environment P

for s in S:
    P[s]=dict()
    
    if (terminal_state(s)):
        P[s][up]=(1.0,s,0.0,True)   # next_state, probability, reward
        P[s][down]=(1.0,s,0.0,True)
        P[s][right]=(1.0,s,0.0,True)
        P[s][left]=(1.0,s,0.0,True)
        
    elif s == 1:
        P[s][up]= (1.0, 1, -1.0 ,False) # next_state, probability, reward
        P[s][down]=(1.0, 4, -1.0 ,False)
        P[s][right]=(1.0, 2, -1.0 ,False)
        P[s][left]=(1.0, 0, -1.0 ,True)
        
    elif s == 2:
        P[s][up]= (1.0, 2, -1.0 ,False) # next_state, probability, reward
        P[s][down]=(1.0, 5, -1.0 ,False)
        P[s][right]=(1.0, 2, -1.0 ,False)
        P[s][left]=(1.0, 1, -1.0 ,False)  
        
    elif s == 3:
        P[s][up]= (1.0, 0, -1.0 ,True) # next_state, probability, reward
        P[s][down]=(1.0, 6, -1.0 ,False)
        P[s][right]=(1.0, 4, -1.0 ,False)
        P[s][left]=(1.0, 3, -1.0 ,False) 
     
    elif s == 4:
        P[s][up]= (1.0, 1, -1.0 ,False) # next_state, probability, reward
        P[s][down]=(1.0, 7, -1.0 ,False)
        P[s][right]=(1.0, 5, -1.0 ,False)
        P[s][left]=(1.0, 3, -1.0 ,False) 
        
    elif s == 5:
        P[s][up]= (1.0, 2, -1.0 ,False) # next_state, probability, reward
        P[s][down]=(1.0, 8, -1.0 ,False)
        P[s][right]=(1.0, 5, -1.0 ,False)
        P[s][left]=(1.0, 4, -1.0 ,False) 
     
    elif s == 6:
        P[s][up]= (1.0, 3, -1.0 ,False) # next_state, probability, reward
        P[s][down]=(1.0, 6, -1.0 ,False)
        P[s][right]=(1.0, 7, -1.0 ,False)
        P[s][left]=(1.0, 6, -1.0 ,False) 
        
    elif s == 7:
        P[s][up]= (1.0, 4, -1.0 ,False) # next_state, probability, reward
        P[s][down]=(1.0, 7, -1.0 ,False)
        P[s][right]=(1.0, 8, -1.0 ,False)
        P[s][left]=(1.0, 6, -1.0 ,False) 
        
    elif s == 8:
        P[s][up]= (1.0, 5, -1.0 ,False) # next_state, probability, reward
        P[s][down]=(1.0, 8, -1.0 ,False)
        P[s][right]=(1.0, 8, -1.0 ,False)
        P[s][left]=(1.0, 7, -1.0 ,False)     
        
print ('No. of states in grid: ', noS)
print ('No. of action options in each state:', noA  ) 


No. of states in grid:  9
No. of action options in each state: 4


In [2]:
P[3][1] # Looking at the transition tupple for third state and taking the 1st action

(1.0, 6, -1.0, False)

In [4]:
random_policy = np.ones([noS, noA]) / noA # random policy is same as taking each action with equal probability
random_policy   # probabilities of taking respective actions(colums) for respective states (rows)

array([[0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25, 0.25]])

In [3]:
P

{0: {0: (1.0, 0, 0.0, True),
  1: (1.0, 0, 0.0, True),
  3: (1.0, 0, 0.0, True),
  2: (1.0, 0, 0.0, True)},
 1: {0: (1.0, 1, -1.0, False),
  1: (1.0, 4, -1.0, False),
  3: (1.0, 2, -1.0, False),
  2: (1.0, 0, -1.0, True)},
 2: {0: (1.0, 2, -1.0, False),
  1: (1.0, 5, -1.0, False),
  3: (1.0, 2, -1.0, False),
  2: (1.0, 1, -1.0, False)},
 3: {0: (1.0, 0, -1.0, True),
  1: (1.0, 6, -1.0, False),
  3: (1.0, 4, -1.0, False),
  2: (1.0, 3, -1.0, False)},
 4: {0: (1.0, 1, -1.0, False),
  1: (1.0, 7, -1.0, False),
  3: (1.0, 5, -1.0, False),
  2: (1.0, 3, -1.0, False)},
 5: {0: (1.0, 2, -1.0, False),
  1: (1.0, 8, -1.0, False),
  3: (1.0, 5, -1.0, False),
  2: (1.0, 4, -1.0, False)},
 6: {0: (1.0, 3, -1.0, False),
  1: (1.0, 6, -1.0, False),
  3: (1.0, 7, -1.0, False),
  2: (1.0, 6, -1.0, False)},
 7: {0: (1.0, 4, -1.0, False),
  1: (1.0, 7, -1.0, False),
  3: (1.0, 8, -1.0, False),
  2: (1.0, 6, -1.0, False)},
 8: {0: (1.0, 5, -1.0, False),
  1: (1.0, 8, -1.0, False),
  3: (1.0, 8, -1.0, Fal

In [5]:
policy_1 = np.zeros([noS,noA]) # making a policy which takes only the second action which is going left from all states
policy_1[:,2] =1
policy_1

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [6]:
def policy_eval(policy, discount_factor=1.0, theta=0.00001):
     # Start with a random (all 0) value function
    V = np.zeros(noS)
    while True:
        # TODO: Implement!
        delta = 0 
        # keep track of this to know when the while loop should end , i.e. the change per loop of a state value goes below theta
        
        for s in range(noS): # looping for all states
            v= 0 
            #initializing v = 0
            
            # Getting the index and action_probability for each state 
            
            for index, action_probability in enumerate(policy[s]):
                prob,state,reward,done = P[s][index]
                # using the Bellman equation 
                v += prob*action_probability*(reward + discount_factor * V[state])
                
            # Calculating the delta 
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v    # updating the value of that state s
            #print(V)
        if delta < theta: # checking if the policy eval has concluded 
            break
       
    return np.array(V)

In [7]:
# Doing policy eval with k loops
# we dont use while, but use for loop with k iterations 

def policy_eval_limited(policy, discount_factor=1.0, theta=0.00001, k=20):
     # Start with a random (all 0) value function
    V = np.zeros(noS)
    for i in range(k):
        # TODO: Implement!
        delta = 0
        
        for s in range(noS):
            v= 0
            for a, action_prob in enumerate(policy[s]):
                prob,state,reward,done = P[s][a]
                v += prob*action_prob*(reward + discount_factor * V[state])
            delta = max(delta, np.abs(v - V[s]))
            V[s] = v
            #print(V)
        #if delta < theta:
            #break
       
    return np.array(V)

In [33]:
V.reshape(3,3)

array([[  0.        , -15.99916512, -22.49881453],
       [-15.99916512, -21.49889629, -24.99871601],
       [-22.49881453, -24.99871601, -26.9986209 ]])

In [8]:
policy_eval(random_policy, discount_factor=1.0, theta = 0.0001)       

array([  0.        , -15.99916512, -22.49881453, -15.99916512,
       -21.49889629, -24.99871601, -22.49881453, -24.99871601,
       -26.9986209 ])

In [9]:
V = policy_eval(random_policy, discount_factor=1.0, theta = 0.0001)  
V

array([  0.        , -15.99916512, -22.49881453, -15.99916512,
       -21.49889629, -24.99871601, -22.49881453, -24.99871601,
       -26.9986209 ])

In [10]:
V2 = policy_eval_limited(policy_1, discount_factor=1.0, theta = 0.001, k=14)
V2

array([  0.,  -1.,  -2., -14., -15., -16., -14., -15., -16.])

In [49]:
v_limited_random = policy_eval_limited(random_policy, discount_factor=1.0, theta = 0.001, k=40)

In [50]:
v_limited_random.reshape(3,3)

array([[  0.        , -14.87833618, -20.90731927],
       [-14.87833618, -20.01716505, -23.27496786],
       [-20.90731927, -23.27496786, -25.14718054]])

In [19]:
V[8]

-26.99862089934679

In [30]:
# v(second state) = action_prob * probability of transition * ( reward + discount_factor* V(prev))
v_ex              = 0.25 * 1.0 * (-1 + 1.0*0)
# v               = 0.25 * 1.0 * ( -1 + 1.0*0.25)

In [31]:
v_ex

-0.1875

In [20]:
V2

array([  0.,  -1.,  -2., -14., -15., -16., -14., -15., -16.])

In [21]:
# Now doing policy iteration also known as policy improvement

In [51]:
def policy_improvement(policy_eval_fn=policy_eval, discount_factor=1.0):
    """
    Policy Improvement Algorithm. Iteratively evaluates and improves a policy
    until an optimal policy is found.
    
    Args:
        env: The OpenAI envrionment.
        policy_eval_fn: Policy Evaluation function that takes 3 arguments:
            policy, env, discount_factor.
        discount_factor: gamma discount factor.
        
    Returns:
        A tuple (policy, V). 
        policy is the optimal policy, a matrix of shape [S, A] where each state s
        contains a valid probability distribution over actions.
        V is the value function for the optimal policy.
        
    """
    # Start with a random policy
    policy = np.ones([noS, noA]) / noA
    
    # A greedy policy is a deterministic policy i.e You have 1 as action probability for some action in every state [not confused]
    # A greedy policy is calculated after we have done policy evaluation i.e. once we know a better way to move around in the grid
        
    def greedy_pol(v):     # evaluating for some value function
        pol = []           # initialize the pol list , which has the index of actions 
        for s in range(9):
            m = []         # a list of values of next states 
            for a in range(4):
                val = v[P[s][a][1]] 
                m.append(val)
            action = np.argmax(np.array(m))  # finding the action which gets maximum value (action recieving max reward)
            pol.append(action)
         
        policy_final = np.zeros([noS, noA]) #initialize the final policy with zeros
        for ind,value in enumerate(pol):
           # print(ind,value)
            policy_final[ind][value] = 1 # assigning 1 i.e. acting greedily wrt to the optimized value function
        return policy_final    
    
    # Now performing this policy eval and getting greedy policy in loops gives us the policy improvement algorithm
    
    pol_new = policy
    prev_pol = np.zeros([noS, noA])
    
    '''
    #doing it for j iterations 
    j = 10
    for k in range(j):
        # Implement this!
        vnew = policy_eval(pol_new,discount_factor=1, theta=0.0001)
        pol_new = greedy_pol(vnew)
        #if prev_pol == pol_new :
        #    break
            
       # prev_pol = pol_new
        #new_pol = act_greedily arg_max of options 
    '''
     # doing it with escape condition
    while True: 
        # Implement this!
        vnew = policy_eval(pol_new,discount_factor=1, theta=0.0001)
        pol_new = greedy_pol(vnew)
        print(pol_new)
        #print(np.argmax(pol_new[0]))
        #print(np.argmax(prev_pol[0]))
        
        # breaking when update per loop is very small 
        
        if np.argmax(pol_new) == np.argmax(prev_pol) :
            break
        
            
        prev_pol = pol_new     # updating the prev policy to compare in the next loop
        
        #new_pol = act_greedily arg_max of options   
        
           
    
    return pol_new, vnew # returning both the optimal policy and the value function

In [52]:
a,b = policy_improvement()

[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]]


In [24]:
P[0][1][1]

0

In [25]:
b

array([  0.        , -15.99916512, -22.49881453, -15.99916512,
       -21.49889629, -24.99871601, -22.49881453, -24.99871601,
       -26.9986209 ])

In [26]:
a


array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
ao = [0,2,2,0,0,0,0,0,0]

In [28]:
print((v_limited_random[P[1][0][1]] + -1) )
print((v_limited_random[P[1][1][1]] + -1) )
print((v_limited_random[P[1][2][1]] + -1) )
print((v_limited_random[P[1][3][1]] + -1) )

m = []


-8.706117655849084
-11.534311711089686
-1.0
-11.722849559155293


In [29]:
# takes policy evaluation step for only one iteration
# i.e. value evaluation limited with k=1

def value_iteration(policy_eval_fn=policy_eval, discount_factor=1.0): 
    """
    Policy Improvement Algorithm. Iteratively evaluates and improves a policy
    until an optimal policy is found.
    
    Args:
        env: The OpenAI envrionment.
        policy_eval_fn: Policy Evaluation function that takes 3 arguments:
            policy, env, discount_factor.
        discount_factor: gamma discount factor.
        
    Returns:
        A tuple (policy, V). 
        policy is the optimal policy, a matrix of shape [S, A] where each state s
        contains a valid probability distribution over actions.
        V is the value function for the optimal policy.
        
    """
    # Start with a random policy
    policy = np.ones([noS, noA]) / noA
    
    # A greedy policy is a deterministic policy i.e You have 1 as action probability for some action in every state [not confused]
    # A greedy policy is calculated after we have done policy evaluation i.e. once we know a better way to move around in the grid
        
    def greedy_pol(v):     # evaluating for some value function
        pol = []           # initialize the pol list , which has the index of actions 
        for s in range(9):
            m = []         # a list of values of next states 
            for a in range(4):
                val = v[P[s][a][1]] 
                m.append(val)
            action = np.argmax(np.array(m))  # finding the action which gets maximum value (action recieving max reward)
            pol.append(action)
         
        policy_final = np.zeros([noS, noA]) #initialize the final policy with zeros
        for ind,value in enumerate(pol):
           # print(ind,value)
            policy_final[ind][value] = 1 # assigning 1 i.e. acting greedily wrt to the optimized value function
        return policy_final    
    
    # Now performing this policy eval and getting greedy policy in loops gives us the policy improvement algorithm
    
    pol_new = policy
    prev_pol = np.zeros([noS, noA])
    
    '''
    #doing it for j iterations 
    j = 10
    for k in range(j):
        # Implement this!
        vnew = policy_eval(pol_new,discount_factor=1, theta=0.0001)
        pol_new = greedy_pol(vnew)
        #if prev_pol == pol_new :
        #    break
            
       # prev_pol = pol_new
        #new_pol = act_greedily arg_max of options 
    '''
     # doing it with escape condition
    while True: 
        # Implement this!
        vnew = policy_eval_limited(pol_new,discount_factor=1, theta=0.0001, k=1) # only change the k to be one i.e update each loop
        pol_new = greedy_pol(vnew)
        #print(np.argmax(pol_new[0]))
        #print(np.argmax(prev_pol[0]))
        
        # breaking when update per loop is very small 
        
        if np.argmax(pol_new) == np.argmax(prev_pol) :
            break
        
            
        prev_pol = pol_new     # updating the prev policy to compare in the next loop
        
        #new_pol = act_greedily arg_max of options   
        
           
    
    return pol_new, vnew # returning both the optimal policy and the value function

In [30]:
c,d = value_iteration()

In [31]:
d

array([ 0.     , -1.     , -1.25   , -1.     , -1.5    , -1.6875 ,
       -1.25   , -1.6875 , -1.84375])

In [32]:
c

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.]])